### ISSUE TITLE
with cashdesk module

### ISSUE THREAD

**Issue by jojorb** [aspangaro/oblyon#20]
hi, first tank you for your work with oblyon, it's amazing!
i did try it on Dolibarr 7.0.0 and activate the cashdesk module.
unfortunately It look a lil messy, i will try to check it.
If you have some hints for a quick fix, that would be awesome

**Comment by madmath03** [comment]
@RobyRemzy I took the liberty to do some fixes on the cashdesk layout with Oblyon.
It turned out that there was unfinished work there (for instance, the logo were present but not used).

Here is a preview of it:
![image](https://user-images.githubusercontent.com/6967675/40628891-11b90f02-62c8-11e8-951b-11a1fafbbe75.png)

Feel free to create new issues if you find anything in particular. I would love to help improve this awesome theme 😃

**Comment by jojorb** [comment]
oh great! awesome @madmath03
